version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-node_modules-{{ checksum "package.json" }}-
            - v1-node-modules-
      - run:
          name: Yarn
          command: |
            yarn install
      - save_cache:
          key: v1-node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
